services:
  ai-module:
    image: ai-module:latest
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    env_file:
      - path: ../ai_module/.env
        required: false
    ports:
      - "8000:8000"
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5